// ⚠️ 请直接从子目录导入以获得更好的 tree-shaking 效果
// 例如: import { NoDataIcon } from '@/components/icons/wallet'
// 此文件仅为兼容保留
export * from './wallet'
export * from './home/gameTypes'
export { default as IosIcon } from './home/bottomArea/IosIcon.svg'
export { default as AndroidIcon } from './home/bottomArea/AndroidIcon.svg'
export { default as PG } from './home/bottomArea/PG.svg'
export { default as AG } from './home/bottomArea/AG.svg'
export { default as BBIN } from './home/bottomArea/BBIN.svg'
export { default as BG } from './home/bottomArea/BG.svg'
export { default as MG } from './home/bottomArea/MG.svg'
export { default as JDB } from './home/bottomArea/JDB.svg'
export { default as FG } from './home/bottomArea/FG.svg'
export { default as WallE } from './home/bottomArea/WallE.svg'
export { default as R88 } from './home/bottomArea/R88.svg'
export { default as SABA } from './home/bottomArea/SABA.svg'
export { default as CQ9 } from './home/bottomArea/CQ9.svg'
export { default as FB } from './home/bottomArea/FB.svg'
export { default as DG } from './home/bottomArea/DG.svg'
export { default as PP } from './home/bottomArea/PP.svg'
export { default as RSG } from './home/bottomArea/RSG.svg'
export { default as FC } from './home/bottomArea/FC.svg'

export { default as BuyuIcon } from './active/rebate/fishing.svg'
export { default as CaipiaoIcon } from './active/rebate/lottery.svg'
export { default as DianziIcon } from './active/rebate/slot.svg'
export { default as DianjingIcon } from './active/rebate/game.svg'
export { default as QipaiIcon } from './active/rebate/card.svg'
export { default as ZhenrenIcon } from './active/rebate/TV.svg'
export { default as TiyuIcon } from './active/rebate/sport.svg'
export * from './active/vip'
export { default as RulesIcon } from './active/vip/RulesIcon'
export { default as NeiRong } from './active/NeiRong'

export { VipIcon } from './active/menu/VipIcon'
export { MissionCenterIcon } from './active/menu/MissionCenterIcon'
export { RebateIcon } from './active/menu/RebateIcon'
export { BeDealtIcon } from './active/menu/BeDealtIcon'
export { MemberDayIcon } from './active/menu/MemberDayIcon'
export { SpecialBonusIcon } from './active/menu/SpecialBonusIcon'
export { TaskRecordIcon } from './active/menu/TaskRecordIcon'
export { TurntableIcon } from './active/menu/TurntableIcon'
export { ReliefIcon } from './active/menu/ReliefIcon'
